### ISSUE TITLE
我遇到了一些问题 I have some problems

### ISSUE THREAD

**Issue by TDarkMatter** [sendino-hashilate/fecmdszls#1]
我按照视频的步骤成功运行了软件，但是只能够添加一个账号并且我运行的时候它打开的并不是我输入的账号而是默认的别人的号。顺便问一下能不能够以此法运行qq游戏的账号？
I followed the steps in the video to run the app successfully, but only one account could be added and when I ran it opened not the account I had entered but someone else's . By the way, can I use this method to run QQ game account?

**Comment by TDarkMatter** [comment]
我尝试加QQ群但是失败了，搜索显示没有这个群。如您不介意我们加个QQ？我的QQ号是3304475209

**Comment by sendino-hashilate** [comment]
这个不是QQ群，我放的群是telegram群，我从未设立过任何QQ与微信等国内社交软件的群聊，望知悉，有问题最好还是加群问会解决快些。关于你说的只能添加一个号的问题，解决方法是，找到文件夹里面的账号ini文件在里面进行修改完成后再启动游戏即可

**Comment by sendino-hashilate** [comment]
对的，QQ号不能运行，另外我不是原作者，有关部分软件具体信息无法告知

**Comment by sendino-hashilate** [comment]
我对于本软件的解释权仅限于破解
